# This has to be an integer. Read more [here](https://core.telegram.org/api/obtaining_api_id) | No quotes
api_id: 26967968 

# Long 32 characters hash identifier. Read more [here](https://core.telegram.org/api/obtaining_api_id) | With quotes
api_hash: '497a03f719faf20a161e4254ed69f86a' 

# Session name. Only one session (with a unique session name) can run at a time | With quotes
session_name: 'forwardgram' 

# Discord Bot Token. Go create a bot on discord. | No quotes
discord_bot_token: 'MTA0NDUyODI0NzY3MDU3MTAyOA.GVR_Ml.qm0w08l62lEAribfOFkH79Qw5IqD3oVwOLOTxA'

# Discord Channels | No quotes
discord_1_channel: 1044563845101912115

#discord webhook
discord_webhooks:
  - 'https://discord.com/api/webhooks/1045018815211241554/iJybdO2zQU9ftN_kibZqnKQWux7S4kVgnAA9L-TUtokEa5jYpVVgSZDWg7DzVGzGOanV'
  - 'https://discord.com/api/webhooks/1045028714884374539/d9bt9gYwlCKpvScH3ePKAn3-Q2pg4vfxy1eUr2f6-McrFK4aOaFyJZ7o2n7zVln9buv6'
  - 'https://discord.com/api/webhooks/1045030083783569509/kNcl8h0NT-zOjAZQ6Fpu59HUdGc3sNCbksZpchX57ShLr38a4XIOTHnlJesn-cIFOfeD'
  - 'https://discord.com/api/webhooks/1045033249711341568/FZQrPSrYswVOYmSmP9p4FiAL7zjMnSaUypxkdw2aKf92xNIGpqaKU15DTTt-BlarE2WU'
  - 'https://discord.com/api/webhooks/1046687680374788106/cfwsuVBfNnfmskK0MUxOYJHImTzNZovqXNHPSKmRD_5j9YsimwI6Y0GjfMhP1cEf_8VT'
  - 'https://discord.com/api/webhooks/1046687175212793987/11zkWURoOS_WOBWLgY9p9BA_AIN2FOj6CmXMslp6C_pJbAuX-HlFnHUHmum9KP7Wwrzi'
  - 'https://discord.com/api/webhooks/1046686454442639390/tHf3ktPZPFAC-DEwDpVCXGGqvugxbKsPX8C3Taep8aCmZ4M2znhWb2JuiSA_cx8l0dQV'
  - 'https://discord.com/api/webhooks/1047590057575448668/oucK8adiArKTp9Bqe34b4R8Nmv6Zw34OxaybIUi-zp_8t4SDsXoctDBATRent8NH0gyA'
  - 'https://discord.com/api/webhooks/1048328376944963634/ULXaIZzYLGGI3BIou3HrpWCneAgL-ZU5l5IAm8OJO59aHDYYWkEhUFCTpeHdhempKy15'
  - 'https://discord.com/api/webhooks/1048496294626336768/cdpBE8eWXzHwlGJvUjJTPEJLVLKZjdjdghxUhoyzGrYZbTj1kztBIgiQbHUr9it4rYgm'
  - 'https://discord.com/api/webhooks/1048500021357719622/vMIGiA50VZXIYJL8LeEwM7L1JL_h_46EycLnvPJZQZAebi4b6Kjg-Qnj7GVt0lhGNaZk'
  - 'https://discord.com/api/webhooks/1048500761300045894/f7SehIKZRDVZ6TF2FeY3k8I0dyNlR9al9kx5vSJp8fCpHJ0efLdWj2oYbQSEUHr_fVqw'
  - 'https://discord.com/api/webhooks/1048501832286228521/ejeMNwuCwIQrmV9go-fgv7nZa9ahp6y_spSXGLnn2vDo_1pufw00vUcMEYowAFyxWbVh'
  - 'https://discord.com/api/webhooks/1048504457274597419/yQs3MmW6l6Mm-S4xVlnSiCp_JoOPcELm7RmZSV6WqVFfv7dhOI4buzssz-yKHQepZE6b'
  - 'https://discord.com/api/webhooks/1048505510099419137/ZOu_LT_5_yr06Pq6ex6Fz_k6YjM49R3GlO1vs9X67igvFbR1x0bLMXI2ITvN_jPHpPWz'
  - 'https://discord.com/api/webhooks/1048506961513160704/7fEeQISzZW7SnMPkw8ENgAcTKZ9JGqIy6k6NyGT_Ly4cPjXlytwhT4c2ugz_gXiozzq8'
  - 'https://discord.com/api/webhooks/1048508566404866068/L4PIwrdponDIqYemv8dmK8FVBl9A2FHjygkkL_d_th6q3UqxpHYRjVCOr8nFdG-HAtWt'
  - 'https://discord.com/api/webhooks/1048509584232415252/X9KP2U9Az9RTxeb5z2Qz_tKrX04ESwMfw6pRR-6iXgLyZfdBYQtavjVM2WOXEOMH7WXS'
  - 'https://discord.com/api/webhooks/1048513212716421120/NtQ4prNz1GtJ7vZnpj9eGiJprvxROES8LzDaysNHeaN6WX1WrLF3hQElw1OK4sU1hBvW'
  - 'https://discord.com/api/webhooks/1048513958325268551/vmEEXdH-oi6lIPv6PtbRJH7l7La7Rbk_DTKS7tliwkPj6qNh7XJfnGuG0HtT5v90upIh'
  - 'https://discord.com/api/webhooks/1048518506561409094/gT3vmyASqeoz-NDpUSAP1LaA0eH7q_2kwLpTx1PYACOUu89sAs-FIu9ErlDgullg36CT'
  - 'https://discord.com/api/webhooks/1048519055834882059/a0gT5AWcxeMr5vZZgJAKVjH1BYWtnMWiufQaqg3B4Y_VGyjp-qauDguO3AhZB8rKGlg8'
  - 'https://discord.com/api/webhooks/1048519510652633098/nFYdPQoFsmwxclPF_tF737LUYtmvaCWkqKadqa5y6J3TSLpAl4F5CIIEH-IXc3szwUnj'
  - 'https://discord.com/api/webhooks/1048520007241453568/CdS_8AJaSKmaN7YaLguhbrCS0_rFQisDwdIADWsYmi-E2bOpQ-7uq1KK1Y78GRS0eZNF'
  - 'https://discord.com/api/webhooks/1048522311155843103/fmtLEldyVZ9_pZPmhA7Dc_X9gPIYX0YhJRn3rFWIY6bX-KATUVy3foUChMaYPzZgMkzw'
  - 'https://discord.com/api/webhooks/1048522810349330432/3pWAYWkdBsOoL9-aadZgYs86bZ40B8B6I3B5HBCGq4HYVqAu9tAMZlB4O8nehbNyWRRD'
  - 'https://discord.com/api/webhooks/1049023360237043734/ABaycnbytH0XQEITttwWgSSBdfTW441Mb-sD5uCI_aGLUR2-G7gudinW6c3JFQZEJVIM' 
  - 'https://discord.com/api/webhooks/1049736706007507034/GuNjFLV8Y7CwhmJai-fxv9qiNSOhYmrCmxE7G3r7vN-YjFhkaiBXuoA0USE29IF6ULcX'
  - 'https://discord.com/api/webhooks/1049737411447500830/W2VQU48uCrbjVxUfIjB7mrm1sxwA5s0OtdHyyS9allhywffuI8tS3zgwRRRooBa73QuC'
  - 'https://discord.com/api/webhooks/1049737872875466853/Cs5kFKiFpFrBGIfUm03B05d28vd9xYIV8nI7pirhpOfpSpVzKbwoRyqhBzsbPjON3Qy3'
  - 'https://discord.com/api/webhooks/1049742619711897660/hTO-4nzraYz3MDcwnm8pYpRFM81wxeWrNTmozHFh4hmjc9eN7PYAN_-Ng8hvzCXRNm2D'
  - 'https://discord.com/api/webhooks/1049742876222951445/wb5AWjqt7IqI_C0CXdRlTm1-0Cl-frc1WyjU6syVrdYqHdnaG6PjbWs1xotDs9lbSm62'
  - 'https://discord.com/api/webhooks/1051196819322970113/xWaXLBX_PvG5fPF-spLlp1DzWI1CF10pGuo1O_jtyvxqqRbizLbOH-WiXqQYTkUzQhax'
  - 'https://discord.com/api/webhooks/1052845579350327316/voIOg5e60Hc98adUhKs9V-5NcD1gPGnOabFaQggyFt-DNoJauQWYXap2Eu_KsKc0A-xl'
  - 'https://discord.com/api/webhooks/1052856634117996575/1zzvOykWpQ6WzHokyTyREhMHWpROAthNSS0a_qwAumPvzKT7lBD0KgRw1-ZGiSrzCGvd'
  - 'https://discord.com/api/webhooks/1052864195407921222/QxM6ucTG6DBlSyrkbSFkNRBR1cZuelkomlQRC_Vljk_YUnGd_KIXC4q0fFHvW0NlkTME'
  - 'https://discord.com/api/webhooks/1052873636106747905/yH_PFpZG4MBhkLFQo-FNEeVvgwsLcFmaR3BYjt0Zdyb_8rrDzbBTIsouyrJAw2ljPTro'
  - 'https://discord.com/api/webhooks/1052877892406743050/iZuqT0Z2-ta_iEK1cmk39427KONwvO3jrFL_20cxyQZUl_4g6RKtWALIeTOfG42_kwXb'
  - 'https://discord.com/api/webhooks/1053585549136498699/h6Yussa4ue5_jNNCJaFuSf7QUkQh01fIob6k489OIgiC_qlYwsPKMZBjF6Psd9m2MujR'
  - 'https://discord.com/api/webhooks/1053588801538248724/gFye4wffZpbGxyonOT9TQ3Po-75dME-Z2Gc7E7lG6JP3d0uTp7krzqe3zNpGsuGRAYnn'
  - 'https://discord.com/api/webhooks/1057996594655539262/oGrCS2IY9Oys2NdvX8indNPm0mCtbL1Jci-g8mS0QOW7f0zwUwSeqdCnEVkgAUiA6CCi'

# The channel names that you'd like to forward messages from. Just add input telegram channel names here.
# The user running the client must have these channels present on it's dialogs. 
input_channel_names:
  - 'GGShot_Bot (Cornix)'
  - 'GreenCrypto Indicator Alerts (Automated)'
  - 'Future. VIP Signal [Private]'
  - '100x Personal trading 50- 50 Profit share'
  - 'Crypto Genix Premium'
  - 'Premium ZONE'
  - 'Beyond Grace'
  - 'PREMIUM'
  - 'Channel Mirror'
  - 'Binance 360 MTC'
  - 'Binance 360 SRV'
  - 'Fed Russian'
  - 'Predictum Indicator'
  - 'Alex Friedman'
  - 'Rose Margin'
  - 'HC Capital'
  - 'Forex Trading'
  - 'GreenCrypto (PREMIUM)'
  - 'Bitcoin Bullets'
  - 'Crypto Jobber Premium'
  - 'Future 125x'
  - 'TradingByCF'
  - 'Latest news'
  - 'Atal Scalp Gang'
  - 'Crypto Coin Coach'
  - 'Crypto Cove'
  - 'Emperaror Latit'
  - 'Crypto Kardana'
  - 'Crypto Proincome'
  - 'Inner Circle'
  - 'Fat Pig Signal'
  - 'Binance Killer'
  - 'TCVN Future Premium'
  - 'GG Players Club'
  - 'Kim Premium'
  - 'Lucky Trade Com'
  - 'Premium Signals'
  - 'CryptoQuant Alert'
  - 'Binance Waves'
  - 'Jack Dorsey Coins'
  - 'Oscar Private Indicator'

# The output channel names that the messages will be forwarded to.
# The user running the client must have a write access to those channels, and have the channels present on theirs dialogs.
output_channel_names: 
  - 'Channel Mirror'

# The channel IDs that you'd like to forward messages from. Just get channel id from channels you put as input_channel_names above (You can get a channel ID by forwarding any message from it to @userinfobot , and removing the -100 from the start ) 
input_channel_ids:
  - 1761588717
  - 1529114320
  - 1161239220
  - 1637855983
  - 1632103125
  - 1573131967
  - 1794333712
  - 1568194689
  - 1437724898
  - 1716527256
  - 1859230943
  - 1672942582
  - 1551901513
  - 1656633694
  - 1541021455
  - 1718929369
  - 1709849281
  - 1791020473
  - 1640927943
  - 1681747941
  - 1676465845
  - 1779248012
  - 1672577148
  - 1824337314
  - 1402889916
  - 1670208530
  - 1753966001
  - 1636766460
  - 1429986806
  - 1554099362
  - 1624090802
  - 1578702573
  - 1709330753
  - 1583146219
  - 1703667117
  - 1897169248
  - 1572964044
  - 1246846205
  - 1259400586
  - 1386020896
  - 1510779619

# The output channel IDs that the messages will be forwarded to. Just get channel id from channels you put as output_channel_names above (You can get a channel ID by forwarding any message from it to @userinfobot , and removing the -100 from the start )
output_channel_ids: 
  - 1437724898

# Do not touch this: 
#input_channel_ids: []
